#+TITLE: Guideline for Contributing
#+DATE: Tuesday, Jul 05 2016
#+OPTIONS: num:t
#+STARTUP: overview

* Getting Started

** Prerequisite

   See README [[https://github.com/foss-np/anubad/tree/experimental#manual][#manual]]

** Coding Style

   Our coding style is loosly based on [[https://www.python.org/dev/peps/pep-0008/][PEP 8]]. *4* *spaces* for
   indentation is the must. We encourage move beyond the PEP 8 and
   code more pythonic way.

** Guidelines for new GNOME developers

   Beyond the prerequisite mentioned above, several tools available
   for assisting the development of *GNOME* application.

*** Recommended tools

    [[https://wiki.gnome.org/Apps/Devhelp][DevHelp]]: An API documentation browser for *GNOME*

    [[http://glade.gnome.org/][Glade]]: A GUI designer for *GTK+ Applications*

    A good *text-editor* or *IDE* (Integrated Development Environment)

* Inside Repository

  There are mainly 3 branches,

  | Branch       | Description                         |
  |--------------+-------------------------------------|
  | master       | current stable working version      |
  | dev          | version for developers              |
  | experimental | unstable branch with latest changes |

  Start with =dev= branch to begin development, =master= branch is
  usually stable branch for common users.

  If you want to be upto date with latest development use
  =experimental= which might be really *unstable*.

** Organization

   #+BEGIN_EXAMPLE
     anubad/
     ├── CONTRIBUTING.org      # this file
     ├── autogen.sh            # for gnome-style build
     ├── configure.ac          # for gnome-style build
     ├── Makefile.am           # for gnome-style build
     ├── default.ini           # default configuration file
     ├── assets/               # icons
     ├── help/                 # help files
     ├── plugins/              # default plugin folder
     │   ├── espeak.py
     │   :
     │   └── number2word.py
     ├── ...
     :
     └── src/                  # source code
         ├── core.py
         ├── main.py
         :
         ├── Makefile          # lists runnable recipies
         └── ui
             ├── home.py       # home ui component
             ├── home.css      # css file for home.py
             :
             └── Makefile      # lists runnable recipies
   #+END_EXAMPLE
* Tricks

  assortment developer friendly interface-engines.

  | Modes                 | Search prefix |
  |-----------------------+---------------|
  | Dump mode             | 'd:'          |
  | Command Line Access   | '$'           |
  | Internal Command Mode | '>'           |
