default: home

verbose3:
	VERBOSE=3 ./home.py

verbose4:
	VERBOSE=4 ./home.py

browser:
	./browser.py

display:
	./view.py

sidebar:
	./sidebar.py

add:
	./add.py

preferences:
	./preferences.py

relations:
	./relations.py

home:
	./home.py
