default: home

searchbar:
	./searchbar.py

sidebar:
	./sidebar.py

display:
	./view.py

relations:
	./relations.py

home:
	./home.py

preferences:
	./preferences.py

explorer:
	./explorer.py

add:
	./add.py
