default: home

searchbar:
	./_searchbar.py

sidebar:
	./_sidebar.py

display:
	./_view.py

relations:
	./_relations.py

home:
	./home.py

preferences:
	./preferences.py

explorer:
	./explorer.py

add:
	./add.py
